spring:
  datasource:
    url: jdbc:mysql://132.232.105.89:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 2+aHwqqLT0..

  redis:
    host: 106.15.33.116
    port: 6379
    password: 123456redis
  kafka:
    bootstrap-servers: 132.232.105.89:9092,106.15.33.116:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: mall
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer