spring:
  datasource:
    url: jdbc:mysql://132.232.105.89:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 2+aHwqqLT0..

  redis:
    host: 106.15.33.116
    port: 6379
    password: 123456redis

